/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { CryptoSneakerContract } from "./CryptoSneaker";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "CryptoSneaker"): CryptoSneakerContract;
    }
  }
}

export { CryptoSneakerContract, CryptoSneakerInstance } from "./CryptoSneaker";
